apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openedx-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <YOUR_GIT_REPO_URL>
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: openedx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
